#!/usr/bin/env python3
"""
Setup wizard for TG AI Poster.

Interactive first-run configuration wizard that helps users
set up their Telegram bot and channel settings.
"""

from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path
from typing import Optional

import yaml


def print_header(text: str) -> None:
    """Print a styled header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")


def print_section(text: str) -> None:
    """Print a section header."""
    print(f"\n>>> {text}")
    print("-" * 40)


def get_input(
    prompt: str,
    default: Optional[str] = None,
    required: bool = True,
    is_secret: bool = False,
) -> str:
    """
    Get user input with optional default value.

    Args:
        prompt: Prompt text
        default: Default value
        required: Whether input is required
        is_secret: Whether to hide input

    Returns:
        str: User input
    """
    if default:
        prompt_text = f"{prompt} [{default}]: "
    else:
        prompt_text = f"{prompt}: "

    while True:
        try:
            if is_secret:
                import getpass
                value = getpass.getpass(prompt_text)
            else:
                value = input(prompt_text).strip()

            if not value:
                if default:
                    return default
                if not required:
                    return ""
                print("This field is required. Please enter a value.")
                continue

            return value

        except KeyboardInterrupt:
            print("\n\nSetup cancelled.")
            sys.exit(1)


def get_bool(prompt: str, default: bool = True) -> bool:
    """Get yes/no input."""
    default_str = "Y/n" if default else "y/N"
    while True:
        value = input(f"{prompt} [{default_str}]: ").strip().lower()
        if not value:
            return default
        if value in ("y", "yes", "true", "1"):
            return True
        if value in ("n", "no", "false", "0"):
            return False
        print("Please enter 'y' or 'n'.")


def get_list(prompt: str, default: list[str] = None) -> list[str]:
    """Get a list of values."""
    default_str = ", ".join(default) if default else ""
    print(f"{prompt}")
    print(f"Enter items separated by commas (or leave empty for default)")
    value = input(f"[{default_str}]: ").strip()

    if not value:
        return default or []

    return [item.strip() for item in value.split(",") if item.strip()]


def create_env_file(config: dict) -> None:
    """Create .env file from configuration."""
    env_path = Path(".env")

    if env_path.exists():
        if not get_bool(".env already exists. Overwrite?", default=False):
            print("Skipping .env creation.")
            return

    env_content = f"""# TG AI Poster Environment Variables
# Generated by setup wizard
# {"=" * 50}

# Telegram Bot
TELEGRAM_BOT_TOKEN={config.get("telegram_bot_token", "")}
TELEGRAM_CHANNEL_ID={config.get("telegram_channel_id", "")}

# Telethon (optional - for user account mode)
TELETHON_API_ID={config.get("telethon_api_id", "")}
TELETHON_API_HASH={config.get("telethon_api_hash", "")}
TELETHON_PHONE={config.get("telethon_phone", "")}

# LLM API Keys
OPENAI_API_KEY={config.get("openai_api_key", "")}
ANTHROPIC_API_KEY={config.get("anthropic_api_key", "")}
DEEPSEEK_API_KEY={config.get("deepseek_api_key", "")}

# Admin
ADMIN_TELEGRAM_ID={config.get("admin_telegram_id", "")}
"""

    env_path.write_text(env_content)
    print(f"Created {env_path}")


def create_config_yaml(config: dict) -> None:
    """Create config.yaml from configuration."""
    config_path = Path("config.yaml")

    yaml_config = {
        "telegram": {
            "bot_token": "${TELEGRAM_BOT_TOKEN}",
            "channel_id": "${TELEGRAM_CHANNEL_ID}",
            "posting_mode": config.get("posting_mode", "bot"),
        },
        "telethon": {
            "api_id": "${TELETHON_API_ID}",
            "api_hash": "${TELETHON_API_HASH}",
            "phone": "${TELETHON_PHONE}",
            "session_path": "sessions/user.session",
        },
        "llm": {
            "provider": config.get("llm_provider", "openai"),
            "model": config.get("llm_model", "gpt-4o"),
            "api_key": "${OPENAI_API_KEY}",
            "max_tokens": 800,
            "temperature": 0.85,
        },
        "channel": {
            "topic": config.get("channel_topic", "AI technologies and automation"),
            "style": config.get("channel_style", "Expert but accessible. Think pieces. No hype."),
            "language": config.get("language", "ru"),
            "post_length_min": 200,
            "post_length_max": 900,
            "emojis_per_post": 3,
            "hashtags_count": 2,
        },
        "schedule": {
            "type": config.get("schedule_type", "fixed"),
            "fixed_times": config.get("fixed_times", ["09:30", "14:00", "20:00"]),
            "timezone": config.get("timezone", "Europe/Moscow"),
            "max_daily_posts": 6,
            "min_interval_minutes": 60,
        },
        "sources": {
            "rss_feeds": config.get("rss_feeds", []),
            "enable_rss": True,
        },
        "safety": {
            "manual_approval": config.get("manual_approval", False),
            "max_daily_posts": 6,
            "similarity_threshold": 0.85,
        },
        "database": {
            "url": "sqlite:///./data/tg_poster.db",
        },
        "admin": {
            "telegram_id": "${ADMIN_TELEGRAM_ID}",
            "notify_on_error": True,
            "notify_on_post": False,
        },
    }

    with open(config_path, "w", encoding="utf-8") as f:
        yaml.dump(yaml_config, f, default_flow_style=False, allow_unicode=True)

    print(f"Created {config_path}")


def create_directories() -> None:
    """Create required directories."""
    dirs = ["data", "logs", "sessions", "llm/prompts"]

    for dir_path in dirs:
        path = Path(dir_path)
        if not path.exists():
            path.mkdir(parents=True, exist_ok=True)
            print(f"Created directory: {dir_path}")


async def test_telegram_connection(token: str, channel_id: str) -> bool:
    """Test Telegram bot connection."""
    try:
        from telegram import Bot
        from telegram.error import TelegramError

        bot = Bot(token=token)

        # Try to get bot info
        me = await bot.get_me()
        print(f"Bot connected: @{me.username}")

        # Try to get chat info
        try:
            chat = await bot.get_chat(channel_id)
            print(f"Channel access confirmed: {chat.title or chat.username}")
            return True
        except TelegramError as e:
            print(f"Warning: Could not access channel: {e}")
            print("Make sure the bot is added as admin to the channel.")
            return False

    except ImportError:
        print("Warning: python-telegram-bot not installed. Skipping connection test.")
        return True
    except Exception as e:
        print(f"Error: {e}")
        return False


async def run_setup_wizard() -> None:
    """Run the interactive setup wizard."""
    print_header("TG AI Poster Setup Wizard")

    print("""
Welcome! This wizard will help you configure your autonomous
Telegram channel manager. You'll need:

  1. A Telegram bot token (from @BotFather)
  2. Your channel ID or username
  3. An OpenAI API key (or Anthropic/DeepSeek)

Let's get started!
""")

    config = {}

    # Telegram configuration
    print_section("Telegram Bot Configuration")

    print("""
To create a Telegram bot:
1. Open Telegram and search for @BotFather
2. Send /newbot and follow the instructions
3. Copy the bot token you receive
""")

    config["telegram_bot_token"] = get_input(
        "Enter your Telegram bot token",
        is_secret=True,
    )

    print("""
Enter your channel ID. This can be:
- Channel username: @mychannel
- Channel ID: -1001234567890 (for private channels)
""")

    config["telegram_channel_id"] = get_input(
        "Enter your channel ID or username",
    )

    # Posting mode
    print_section("Posting Mode")

    print("""
Choose how to post to your channel:

1. Bot Mode (recommended)
   - Posts show "via @yourbot" label
   - Safe and official
   - No ban risk

2. Telethon Mode (advanced)
   - Posts appear as regular user messages
   - Requires dedicated Telegram account
   - Risk of account ban if detected
""")

    mode = get_input("Posting mode", default="bot")
    config["posting_mode"] = "telethon" if mode.lower() in ("2", "telethon", "user") else "bot"

    if config["posting_mode"] == "telethon":
        print("\nTelethon requires API credentials from https://my.telegram.org")
        config["telethon_api_id"] = get_input("API ID", required=False)
        config["telethon_api_hash"] = get_input("API Hash", required=False, is_secret=True)
        config["telethon_phone"] = get_input("Phone number (with country code)", required=False)

    # LLM Configuration
    print_section("LLM Configuration")

    print("""
Choose your LLM provider:

1. OpenAI (gpt-4o, gpt-4o-mini)
2. Anthropic Claude (claude-3-opus, claude-3-sonnet)
3. DeepSeek
""")

    provider_choice = get_input("LLM provider", default="1")
    provider_map = {"1": "openai", "2": "claude", "3": "deepseek"}
    config["llm_provider"] = provider_map.get(provider_choice, "openai")

    if config["llm_provider"] == "openai":
        config["llm_model"] = get_input("Model name", default="gpt-4o")
        config["openai_api_key"] = get_input("OpenAI API key", is_secret=True)
    elif config["llm_provider"] == "claude":
        config["llm_model"] = get_input("Model name", default="claude-3-5-sonnet-20241022")
        config["anthropic_api_key"] = get_input("Anthropic API key", is_secret=True)
    else:
        config["llm_model"] = get_input("Model name", default="deepseek-chat")
        config["deepseek_api_key"] = get_input("DeepSeek API key", is_secret=True)

    # Channel configuration
    print_section("Channel Content Settings")

    config["channel_topic"] = get_input(
        "Channel topic/niche",
        default="AI tools and automation for business",
    )

    config["channel_style"] = get_input(
        "Writing style",
        default="Expert practitioner. No hype. Real cases. Telegram-friendly.",
    )

    config["language"] = get_input(
        "Content language (ru/en)",
        default="ru",
    )

    # Schedule configuration
    print_section("Posting Schedule")

    print("""
Choose schedule type:

1. Fixed times - Post at specific times each day
2. Interval - Post every N hours
3. Random - Post at random times within a window
""")

    schedule_choice = get_input("Schedule type", default="1")
    schedule_map = {"1": "fixed", "2": "interval", "3": "random"}
    config["schedule_type"] = schedule_map.get(schedule_choice, "fixed")

    if config["schedule_type"] == "fixed":
        config["fixed_times"] = get_list(
            "Posting times (HH:MM format)",
            default=["09:30", "14:00", "20:00"],
        )
    elif config["schedule_type"] == "interval":
        config["interval_hours"] = get_input("Hours between posts", default="4")

    config["timezone"] = get_input("Timezone", default="Europe/Moscow")

    # Sources configuration
    print_section("Content Sources")

    print("""
Enter RSS feed URLs for content sources.
The system will collect topics from these feeds.
""")

    config["rss_feeds"] = get_list(
        "RSS feed URLs",
        default=[
            "https://feeds.feedburner.com/oreilly/radar",
            "https://hnrss.org/frontpage",
        ],
    )

    # Safety settings
    print_section("Safety Settings")

    config["manual_approval"] = get_bool(
        "Enable manual approval before posting?",
        default=False,
    )

    # Admin settings
    print_section("Admin Notifications")

    print("""
Enter your Telegram user ID for admin notifications.
You can get your ID from @userinfobot on Telegram.
""")

    config["admin_telegram_id"] = get_input(
        "Your Telegram user ID",
        required=False,
    )

    # Create files
    print_section("Creating Configuration Files")

    create_directories()
    create_env_file(config)
    create_config_yaml(config)

    # Test connection
    print_section("Testing Connection")

    print("Testing Telegram bot connection...")
    await test_telegram_connection(
        config["telegram_bot_token"],
        config["telegram_channel_id"],
    )

    # Final steps
    print_header("Setup Complete!")

    print("""
Configuration files created:
  - .env (contains secrets - DO NOT commit to git!)
  - config.yaml (contains settings)

Next steps:

1. Review and adjust settings in config.yaml

2. Initialize the database:
   python main.py --init-db

3. Test with dry run:
   python main.py --dry-run --once

4. Start the scheduler:
   python main.py

For more options:
   python main.py --help

Happy posting!
""")


def main() -> None:
    """Main entry point."""
    try:
        asyncio.run(run_setup_wizard())
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
    except Exception as e:
        print(f"\nError during setup: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
